


panel = '''
██╗░░██╗░█████╗░███╗░░██╗░██████╗░███╗░░░███╗░█████╗░███╗░░██╗
██║░░██║██╔══██╗████╗░██║██╔════╝░████╗░████║██╔══██╗████╗░██║
███████║███████║██╔██╗██║██║░░██╗░██╔████╔██║███████║██╔██╗██║
██╔══██║██╔══██║██║╚████║██║░░╚██╗██║╚██╔╝██║██╔══██║██║╚████║
██║░░██║██║░░██║██║░╚███║╚██████╔╝██║░╚═╝░██║██║░░██║██║░╚███║
╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░╚═════╝░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝                                                                                                                                          
'''

panel_zszazi = '''

                                    █▄▄ █▄█   ▀█ █▀ ▀█ ▄▀█ ▀█ █
                                    █▄█ ░█░   █▄ ▄█ █▄ █▀█ █▄ █


'''


stages = ['''
 +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========
''', '''
  +---+
  |   |
      |
      |
      |
      |
=========
''']


country = [
            'Afghanistan' ,
            'Albania' ,
            'Algeria' ,
            'Andorra' ,
            'Angola' ,
            'Antigua & Deps' ,
            'Argentina' ,
            'Armenia' ,
            'Australia' ,
            'Austria' ,
            'Azerbaijan' ,
            'Bahamas' ,
            'Bahrain' ,
            'Bangladesh' ,
            'Barbados' ,
            'Belarus' ,
            'Belgium' ,
            'Belize' ,
            'Benin' ,
            'Bhutan' ,
            'Bolivia' ,
            'Bosnia Herzegovina' ,
            'Botswana' ,
            'Brazil' ,
            'Brunei' ,
            'Bulgaria' ,
            'Burkina' ,
            'Burundi' ,
            'Cambodia' ,
            'Cameroon' ,
            'Canada' ,
            'Cape Verde' ,
            'Central African Rep' ,
            'Chad' ,
            'Chile' ,
            'China' ,
            'Colombia' ,
            'Comoros' ,
            'Congo' ,
            'Congo {Democratic Rep}' ,
            'Costa Rica' ,
            'Croatia' ,
            'Cuba' ,
            'Cyprus' ,
            'Czech Republic' ,
            'Denmark' ,
            'Djibouti' ,
            'Dominica' ,
            'Dominican Republic' ,
            'East Timor' ,
            'Ecuador' ,
            'Egypt' ,
            'El Salvador' ,
            'Equatorial Guinea' ,
            'Eritrea' ,
            'Estonia' ,
            'Ethiopia' ,
            'Fiji' ,
            'Finland' ,
            'France' ,
            'Gabon' ,
            'Gambia' ,
            'Georgia' ,
            'Germany' ,
            'Ghana' ,
            'Greece' ,
            'Grenada' ,
            'Guatemala' ,
            'Guinea' ,
            'Guinea-Bissau' ,
            'Guyana' ,
            'Haiti' ,
            'Honduras' ,
            'Hungary' ,
            'Iceland' ,
            'India' ,
            'Indonesia' ,
            'Iran' ,
            'Iraq' ,
            'Ireland' ,
            'Israel' ,
            'Italy' ,
            'Ivory Coast' ,
            'Jamaica' ,
            'Japan' ,
            'Jordan' ,
            'Kazakhstan' ,
            'Kenya' ,
            'Kiribati' ,
            'Korea North' ,
            'Korea South' ,
            'Kosovo' ,
            'Kuwait' ,
            'Kyrgyzstan' ,
            'Laos' ,
            'Latvia' ,
            'Lebanon' ,
            'Lesotho' ,
            'Liberia' ,
            'Libya' ,
            'Liechtenstein' ,
            'Lithuania' ,
            'Luxembourg' ,
            'Macedonia' ,
            'Madagascar' ,
            'Malawi' ,
            'Malaysia' ,
            'Maldives' ,
            'Mali' ,
            'Malta' ,
            'Marshall Islands' ,
            'Mauritania' ,
            'Mauritius' ,
            'Mexico' ,
            'Micronesia' ,
            'Moldova' ,
            'Monaco' ,
            'Mongolia' ,
            'Montenegro' ,
            'Morocco' ,
            'Mozambique' ,
            'Myanmar' ,
            'Namibia' ,
            'Nauru' ,
            'Nepal' ,
            'Netherlands' ,
            'New Zealand' ,
            'Nicaragua' ,
            'Niger' ,
            'Nigeria' ,
            'Norway' ,
            'Oman' ,
            'Pakistan' ,
            'Palau' ,
            'Panama' ,
            'Papua New Guinea' ,
            'Paraguay' ,
            'Peru' ,
            'Philippines' ,
            'Poland' ,
            'Portugal' ,
            'Qatar' ,
            'Romania' ,
            'Russian Federation' ,
            'Rwanda' ,
            'St Kitts & Nevis' ,
            'St Lucia' ,
            'Saint Vincent & the Grenadines' ,
            'Samoa' ,
            'San Marino' ,
            'Sao Tome & Principe' ,
            'Saudi Arabia' ,
            'Senegal' ,
            'Serbia' ,
            'Seychelles' ,
            'Sierra Leone' ,
            'Singapore' ,
            'Slovakia' ,
            'Slovenia' ,
            'Solomon Islands' ,
            'Somalia' ,
            'South Africa' ,
            'South Sudan' ,
            'Spain' ,
            'Sri Lanka' ,
            'Sudan' ,
            'Suriname' ,
            'Swaziland' ,
            'Sweden' ,
            'Switzerland' ,
            'Syria' ,
            'Taiwan' ,
            'Tajikistan' ,
            'Tanzania' ,
            'Thailand' ,
            'Togo' ,
            'Tonga' ,
            'Trinidad & Tobago' ,
            'Tunisia' ,
            'Turkey' ,
            'Turkmenistan' ,
            'Tuvalu' ,
            'Uganda' ,
            'Ukraine' ,
            'United Arab Emirates' ,
            'United Kingdom' ,
            'United States' ,
            'Uruguay' ,
            'Uzbekistan' ,
            'Vanuatu' ,
            'Vatican City' ,
            'Venezuela' ,
            'Vietnam' ,
            'Yemen' ,
            'Zambia' ,
            'Zimbabwe'
]


capital = [
            "capital" ,
            "Sukhumi" ,
            "Kabul" ,
            "Episkopi Cantonment" ,
            "Tirana" ,
            "Algiers" ,
            "Pago Pago" ,
            "Andorra la Vella" ,
            "Luanda" ,
            "The Valley" ,
            "St. John's" ,
            "Buenos Aires" ,
            "Yerevan" ,
            "Oranjestad" ,
            "Georgetown" ,
            "Canberra" ,
            "Vienna" ,
            "Baku" ,
            "Nassau" ,
            "Manama" ,
            "Dhaka" ,
            "Bridgetown" ,
            "Minsk" ,
            "Brussels" ,
            "Belmopan" ,
            "Porto-Novo" ,
            "Hamilton" ,
            "Thimphu" ,
            "Sucre" ,
            "La Paz" ,
            "Sarajevo" ,
            "Gaborone" ,
            "Brasília" ,
            "Road Town" ,
            "Bandar Seri Begawan" ,
            "Sofia" ,
            "Ouagadougou" ,
            "Bujumbura" ,
            "Phnom Penh" ,
            "Yaoundé" ,
            "Ottawa" ,
            "Praia" ,
            "George Town" ,
            "Bangui" ,
            "N'Djamena" ,
            "Santiago" ,
            "Beijing" ,
            "Flying Fish Cove" ,
            "West Island" ,
            "Bogotá" ,
            "Moroni" ,
            "Avarua" ,
            "San José" ,
            "Zagreb" ,
            "Havana" ,
            "Willemstad" ,
            "Nicosia" ,
            "Prague" ,
            "Yamoussoukro" ,
            "Kinshasa" ,
            "Copenhagen" ,
            "Djibouti" ,
            "Roseau" ,
            "Santo Domingo" ,
            "Dili" ,
            "Hanga Roa" ,
            "Quito" ,
            "Cairo" ,
            "San Salvador" ,
            "Malabo" ,
            "Asmara" ,
            "Tallinn" ,
            "Addis Ababa" ,
            "Stanley" ,
            "Tórshavn" ,
            "Palikir" ,
            "Suva" ,
            "Helsinki" ,
            "Paris" ,
            "Cayenne" ,
            "Papeete" ,
            "Libreville" ,
            "Banjul" ,
            "Tbilisi" ,
            "Berlin" ,
            "Accra" ,
            "Gibraltar" ,
            "Athens" ,
            "Nuuk" ,
            "St. George's" ,
            "Hagåtña" ,
            "Guatemala City" ,
            "St. Peter Port" ,
            "Conakry" ,
            "Bissau" ,
            "Georgetown" ,
            "Port-au-Prince" ,
            "Tegucigalpa" ,
            "Budapest" ,
            "Reykjavík" ,
            "New Delhi" ,
            "Jakarta" ,
            "Tehran" ,
            "Baghdad" ,
            "Dublin" ,
            "Douglas" ,
            "Jerusalem" ,
            "Rome" ,
            "Kingston" ,
            "Tokyo" ,
            "St. Helier" ,
            "Amman" ,
            "Astana" ,
            "Nairobi" ,
            "Tarawa" ,
            "Pristina" ,
            "Kuwait City" ,
            "Bishkek" ,
            "Vientiane" ,
            "Riga" ,
            "Beirut" ,
            "Maseru" ,
            "Monrovia" ,
            "Tripoli" ,
            "Vaduz" ,
            "Vilnius" ,
            "Luxembourg" ,
            "Skopje" ,
            "Antananarivo" ,
            "Lilongwe" ,
            "Kuala Lumpur" ,
            "Malé" ,
            "Bamako" ,
            "Valletta" ,
            "Majuro" ,
            "Nouakchott" ,
            "Port Louis" ,
            "Mexico City" ,
            "Chisinau" ,
            "Monaco" ,
            "Ulaanbaatar" ,
            "Podgorica" ,
            "Plymouth" ,
            "Rabat" ,
            "Maputo" ,
            "Naypyidaw" ,
            "Stepanakert" ,
            "Windhoek" ,
            "Yaren" ,
            "Kathmandu" ,
            "Amsterdam" ,
            "Nouméa" ,
            "Wellington" ,
            "Managua" ,
            "Niamey" ,
            "Abuja" ,
            "Alofi" ,
            "Kingston" ,
            "Pyongyang" ,
            "Nicosia" ,
            "Belfast" ,
            "Saipan" ,
            "Oslo" ,
            "Muscat" ,
            "Islamabad" ,
            "Ngerulmud" ,
            "Jerusalem" ,
            "Panama City" ,
            "Port Moresby" ,
            "Asunción" ,
            "Lima" ,
            "Manila" ,
            "Adamstown" ,
            "Warsaw" ,
            "Lisbon" ,
            "San Juan" ,
            "Doha" ,
            "Taipei" ,
            "Brazzaville" ,
            "Bucharest" ,
            "Moscow" ,
            "Kigali" ,
            "Gustavia" ,
            "Jamestown" ,
            "Basseterre" ,
            "Castries" ,
            "Marigot" ,
            "St. Pierre" ,
            "Kingstown" ,
            "Apia" ,
            "San Marino" ,
            "Riyadh" ,
            "Edinburgh" ,
            "Dakar" ,
            "Belgrade" ,
            "Victoria" ,
            "Freetown" ,
            "Singapore" ,
            "Philipsburg" ,
            "Bratislava" ,
            "Ljubljana" ,
            "Honiara" ,
            "Mogadishu" ,
            "Hargeisa" ,
            "Pretoria" ,
            "Grytviken" ,
            "Seoul" ,
            "Tskhinvali" ,
            "Juba" ,
            "Madrid" ,
            "Sri Jayawardenapura Kotte" ,
            "Khartoum" ,
            "Paramaribo" ,
            "Mbabane" ,
            "Stockholm" ,
            "Bern" ,
            "Damascus" ,
            "São Tomé" ,
            "Dushanbe" ,
            "Dodoma" ,
            "Bangkok" ,
            "Lomé" ,
            "Nukuʻalofa" ,
            "Tiraspol" ,
            "Port of Spain" ,
            "Edinburgh of the Seven Seas" ,
            "Tunis" ,
            "Ankara" ,
            "Ashgabat" ,
            "Cockburn Town" ,
            "Funafuti" ,
            "Kampala" ,
            "Kiev" ,
            "Abu Dhabi" ,
            "London" ,
            "Washington" ,
            "Charlotte Amalie" ,
            "Montevideo" ,
            "Tashkent" ,
            "Port Vila" ,
            "Vatican City" ,
            "Caracas" ,
            "Hanoi" ,
            "Cardiff" ,
            "Mata-Utu" ,
            "El Aaiún" ,
            "Sanaá" ,
            "Lusaka" ,
            "Harare"   
]


actors = [
            'Harrison Ford' ,
            'Samuel L. Jackson' ,
            'Morgan Freeman' ,
            'Tom Hanks' ,
            'Robert Downey' ,
            'Eddie Murphy' ,
            'Tom Cruise' ,
            'Johnny Depp' ,
            'Michael Caine' ,
            'Scarlett Johansson' ,
            'Gary Oldman' ,
            'Robin Williams' ,
            'Bruce Willis' ,
            'Stellan Skarsgard' ,
            'Anthony Daniels' ,
            'Ian McKellen' ,
            'Will Smith' ,
            'Stanley Tucci' ,
            'Matt Damon' ,
            'Robert DeNiro' ,
            'Cameron Diaz' ,
            'Liam Neeson' ,
            'Andy Serkis' ,
            'Don Cheadle' ,
            'Ben Stiller' ,
            'Helena Bonham Carter' ,
            'Orlando Bloom' ,
            'Woody Harrelson' ,
            'Cate Blanchett' ,
            'Julia Roberts' ,
            'Elizabeth Banks' ,
            'Ralph Fiennes' ,
            'Emma Watson' ,
            'Tommy Lee Jones' ,
            'Brad Pitt' ,
            'Adam Sandler' ,
            'Daniel Radcliffe' ,
            'Jonah Hill' ,
            'Owen Wilson' ,
            'Idris Elba' ,
            'Bradley Cooper' ,
            'Mark Wahlberg' ,
            'Jim Carrey' ,
            'Dustin Hoffman' ,
            'Leonardo DiCaprio' ,
            'Jeremy Renner' ,
            'Philip Seymour Hoffman' ,
            'Sandra Bullock' ,
            'Chris Evans' ,
            'Anne Hathaway' 
]

football = [
                'Arouna Kone' ,
                'Roberto Soldado' ,
                'Loic Remy' ,
                'Mats Hummels' ,
                'Falcao' ,
                'Christian Eriksen' ,
                'Younes Belhanda' ,
                'Mario Mandzukic' ,
                'Javi Martinez' ,
                'Bas Dost' ,
                'Raul' ,
                'Fernando Llorente' ,
                'Mesut Özil' ,
                'Jan Vertonghen' ,
                'Antonio Di Natale' ,
                'Luuk de Jong' ,
                'Shinji Kagawa' ,
                'Lars Bender' ,
                'Andrea Pirlo' ,
                'Michael Carrick' ,
                'Laurent Koscielny' ,
                'Yaya Toure' ,
                'Zlatan Ibrahimovic' ,
                'Xabi Alonso' ,
                'Alex Song' ,
                'Edinson Cavani' ,
                'Scott Parker' ,
                'Karim Benzema' ,
                'Arjen Robben' ,
                'Mario Gomez' ,
                'David Silva' ,
                'Nene' ,
                'Eden Hazard' ,
                'Mikel Arteta' ,
                'Santiago Cazorla' ,
                'Papiss Demba Cisse' ,
                'Claudio Pizarro' ,
                'Luka Modric' ,
                'Bastian Schweinsteiger' ,
                'Klaas-Jan Huntelaar' ,
                'Cesc Fabregas' ,
                'Wayne Rooney' ,
                'Robert Lewandowski' ,
                'Antonio Valencia' ,
                'Franck Ribery' ,
                'Xavi' ,
                'Marco Reus' ,
                'Cristiano Ronaldo' ,
                'Lionel Messi' ,
                'Robin Van Persie'
]

ipl_players = [
                'Abhinav Mukund' ,
                'Albie Morkel' ,
                'Anirudha Srikkanth' ,
                'Chamara Kapugedera' ,
                'Jacob Oram' ,
                'Joginder Sharma' ,
                'KB Arun Karthik' ,
                'Lakshmipathy Balaji' ,
                'Kambala Sumanth' ,
                'Makhaya Ntini' ,
                'Manpreet Gony' ,
                'Matthew Hayden' ,
                'Mike Hussey' ,
                'Muttiah Muralitharan' ,
                'Napoleon Einstein' ,
                'Palani Amarnath' ,
                'Parthiv Patel' ,
                'Ravichandran Ashwin' ,
                'Selvam Suresh Kumar' ,
                'Shadab Jakati' ,
                'Stephen Fleming' ,
                'Subramaniam Badrinath' ,
                'Sudeep Tyagi' ,
                'Suresh Raina' ,
                'Vidyut Sivaramakrishnan' ,
                'Viraj Kadbe' ,
                'Adam Gilchrist' ,
                'Andrew Symonds' ,
                'Arjun Yadav' ,
                'Chamara Silva' ,
                'Chaminda Vaas' ,
                'Doddapaneni Kalyankrishna' ,
                'Dwaraka Ravi Teja' ,
                'Halhadar Das' ,
                'Herschelle Gibbs' ,
                'Mohnish Mishra' ,
                'Nuwan Zoysa' ,
                'Paidikalva Vijaykumar' ,
                'PM Sarvesh Kumar' ,
                'Pragyan Ojha' ,
                'R. P. Singh' ,
                'POLAVARAPU JASWANTH' ,
                'Sanjay Bangar' ,
                'Shahid Afridi' ,
                'Scott Styris' ,
                'V.V.S. Laxman' ,
                'Yalaka Venugopal Rao' ,
                'AB de Villiers' ,
                'Amit Mishra' ,
                'Brett Geeves' ,
                'Daniel Vettori' ,
                'Dinesh Karthik' ,
                'Farveez Maharoof' ,
                'Gautam Gambhir' ,
                'Glenn McGrath' ,
                'Manoj Tiwary' ,
                'Mayank Tehlan' ,
                'Mithun Manhas' ,
                'Mohammad Asif' ,
                'Pradeep Sangwan' ,
                'Rajat Bhatia' ,
                'Shikhar Dhawan' ,
                'Shoaib Malik' ,
                'Sumit Narwal' ,
                'Tejashwi Yadav' ,
                'Tillakaratne Dilshan' ,
                'Virender Sehwag' ,
                'Yogesh Nagar' ,
                'Yo Mahesh' ,
                'Aakash Chopra' ,
                'Ajantha Mendis' ,
                'Ajit Agarkar' ,
                'Ashok Dinda' ,
                'Brad Hodge' ,
                'Brendon McCullum' ,
                'Cheteshwar Pujara' ,
                'Chris Gayle' ,
                'David Hussey' ,
                'Debabrata Das' ,
                'Iqbal Abdulla' ,
                'Ishant Sharma' ,
                'Laxmi Ratan Shukla' ,
                'Mashrafe Mortaza' ,
                'Mohammad Hafeez' ,
                'Murali Kartik' ,
                'Ranadeb Bose' ,
                'Ricky Ponting' ,
                'Rohan Banerjee' ,
                'Salman Butt' ,
                'Saurasish Lahiri' ,
                'Shoaib Akhtar' ,
                'Siddarth Kaul' ,
                'Sourav Ganguly' ,
                'Tatenda Taibu' ,
                'Umar Gul' ,
                'Wriddhiman Saha' ,
                'Yashpal Singh' ,
                'Ajitesh Argal' ,
                'Azhar Mehmood' ,
                'Brett Lee' ,
                'Fidel Edwards' ,
                'Gagandeep Singh' ,
                'Irfan Pathan' ,
                'James Hopes' ,
                'Karan Goel' ,
                'Kumar Sangakkara' ,
                'Kyle Mills' ,
                'Luke Pomersbach' ,
                'Mahela Jayawardene' ,
                'Nitin Saini' ,
                'Pankaj Dharmani' ,
                'Piyush Chawla' ,
                'Ramesh Powar' ,
                'Ramnaresh Sarwan' ,
                'Rishi Dhawan' ,
                'Sahil Kukreja' ,
                'Shaun Marsh' ,
                'Simon Katich' ,
                'Sreesanth' ,
                'Sunny Sohal' ,
                'Tanmay Srivastava' ,
                'Uday Kaul' ,
                'V. R. V. Singh' ,
                'Wilkin Mota' ,
                'Yuvraj Singh' ,
                'Abhishek Nayar' ,
                'Ajinkya Rahane' ,
                'André Nel' ,
                'Ankeet Chavan' ,
                'Ashwell Prince' ,
                'Ashish Nehra' ,
                'Dhawal Kulkarni' ,
                'Dilhara Fernando' ,
                'Dominic Thornley' ,
                'Dwayne Bravo' ,
                'Dwayne Smith' ,
                'Gaurav Dhiman' ,
                'Harbhajan Singh' ,
                'Lasith Malinga' ,
                'Loots Bosman' ,
                'Luke Ronchi' ,
                'Manish Pandey' ,
                'Mohammad Ashraful' ,
                'Musavir Khote' ,
                'Pinal Shah' ,
                'Rajesh Pawar' ,
                'Robin Uthappa' ,
                'Rohan Raje' ,
                'Sachin Tendulkar' ,
                'Sanath Jayasuriya' ,
                'Saurabh Tiwary' ,
                'Shaun Pollock' ,
                'Siddharth Chitnis' ,
                'Swapnil Singh' ,
                'Vikrant Yeligati' ,
                'Yogesh Takawale' ,
                'Abdur Razzak' ,
                'Anil Kumble' ,
                'Ashley Noffke' ,
                'Balachandra Akhil' ,
                'Bharat Chipli' ,
                'Cameron White' ,
                'Dale Steyn' ,
                'Devraj Patil' ,
                'Jacques Kallis' ,
                'Jagadeesh Arunkumar' ,
                'KP Appanna' ,
                'Mark Boucher' ,
                'Misbah-ul-Haq' ,
                'Nathan Bracken' ,
                'Neravanda Aiyappa' ,
                'Praveen Kumar' ,
                'Rahul Dravid' ,
                'Ross Taylor' ,
                'Shivnarine Chanderpaul' ,
                'Shreevats Goswami' ,
                'Sunil Joshi' ,
                'Vinay Kumar' ,
                'Virat Kohli' ,
                'Wasim Jaffer' ,
                'Zaheer Khan' ,
                'Abhishek Raut' ,
                'Aditya Angle' ,
                'Anup Revandkar' ,
                'Darren Lehmann' ,
                'Dimitri Mascarenhas' ,
                'Dinesh Salunkhe' ,
                'Faiz Fazal' ,
                'Graeme Smith' ,
                'Jaydev Shah' ,
                'Justin Langer' ,
                'Kamran Akmal' ,
                'Mahesh Rawat' ,
                'Mohammad Kaif' ,
                'Morne Morkel' ,
                'Munaf Patel' ,
                'Niraj Patel' ,
                'Pankaj Singh' ,
                'Parag More' ,
                'Ravindra Jadeja' ,
                'Shane Warne' ,
                'Aswanth Reddi' ,
                'Siddharth Trivedi' ,
                'Sohail Tanvir' ,
                'Sumit Khatri' ,
                'Swapnil Asnodkar' ,
                'Taruwar Kohli' ,
                'Younis Khan' ,
                'Yusuf Pathan' ,
                'Andrew Flintoff' ,
                'George Bailey' ,
                'Murali Vijay' ,
                'Thilan Thushara' ,
                'Abhinav Kumar' ,
                'Azhar Bilakhia' ,
                'Harmeet Singh' ,
                'Jaskaran Singh' ,
                'Kemar Roach' ,
                'Manvinder Bisla' ,
                'Mitchell Marsh' ,
                'Rahul Sharma' ,
                'Ryan Harris' ,
                'Shoaib Ahmed' ,
                'Tirumalasetti Suman' ,
                'Aavishkar Salvi' ,
                'Andrew McDonald' ,
                'David Warner' ,
                'Dirk Nannes' ,
                'Owais Shah' ,
                'Paul Collingwood' ,
                'Umesh Yadav' ,
                'Wayne Parnell' ,
                'Angelo Mathews' ,
                'Anureet Singh' ,
                'Arindam Ghosh' ,
                'Charl Langeveldt' ,
                'Moises Henriques' ,
                'Morné van Wyk' ,
                'Sachin Rana' ,
                'Shoaib Shaikh' ,
                'Amanpreet Singh' ,
                'Burt Cockley' ,
                'Jerome Taylor' ,
                'Ravi Bopara' ,
                'Ravikant Shukla' ,
                'Rusty Theron' ,
                'Ryan Ninan' ,
                'Vikramjeet Malik' ,
                'Yusuf Abdulla' ,
                'Abu Nechim Ahmed' ,
                'Chentanya Nanda' ,
                'Graham Napier' ,
                'JP Duminy' ,
                'Rahil Shaikh' ,
                'Ryan McLaren' ,
                'Abhimanyu Mithun' ,
                'Bhuvneshwar Kumar' ,
                'CM Gautam' ,
                'Dillon du Preez' ,
                'Eoin Morgan' ,
                'Ishank Jaggi' ,
                'Jesse Ryder' ,
                'Jitendra Patil' ,
                'Karn Sharma' ,
                'Kedar Jadhav' ,
                'Kevin Pietersen' ,
                'Rajesh Bishnoi' ,
                'Raju Bhatkal' ,
                'Rangaraj Suthesh' ,
                'RK Sabharwal' ,
                'Roelof van der Merwe' ,
                'Saurabh Bandekar' ,
                'Sreenath Aravind' ,
                'Tinu Yohannan' ,
                'Udit Patel' ,
                'Abdulahad Malek' ,
                'Aditya Dole' ,
                'Amit Singh' ,
                'Ashraf Makda' ,
                'Atul Sharma' ,
                'Gajendra Singh' ,
                'Johan Botha' ,
                'Kamran Khan' ,
                'Lee Carseldine' ,
                'Mohammed Arif' ,
                'Naman Ojha' ,
                'Paras Dogra' ,
                'Paul Valthaty' ,
                'Pushkaraj Chavan' ,
                'Raiphi Gomez' ,
                'Rob Quiney' ,
                'Shaun Tait' ,
                'Shrideep Mangela' ,
                'Tyron Henderson' ,
                'Chandrasekar Ganapathy' ,
                'Doug Bollinger' ,
                'Hemang Badani' ,
                'Justin Kemp' ,
                'Thisara Perera' ,
                'Anirudh Singh' ,
                'Ashish Reddy' ,
                'Bodapati Sumanth' ,
                'Joginder Singh' ,
                'Sarabjit Ladda' ,
                'Sarandeep Singh' ,
                'Shashi Ranjan' ,
                'Chirag Pathak' ,
                'Eklak Ahmid' ,
                'Ganapathi Vignesh' ,
                'Harshad Khadiwale' ,
                'Jaydev Unadkat' ,
                'Mandeep Singh' ,
                'Rohan Gavaskar' ,
                'Shane Bond' ,
                'Varun Aaron' ,
                'Adrian Barath' ,
                'Bipul Sharma' ,
                'Love Ablish' ,
                'Reetinder Singh Sodhi' ,
                'Shalabh Srivastava' ,
                'Aditya Tare' ,
                'Ali Murtaza' ,
                'Ambati Rayudu' ,
                'Chandan Madan' ,
                'Ishan Malhotra' ,
                'Kieron Pollard' ,
                'Rahul Shukla' ,
                'Rajagopal Sathish' ,
                'Stuart Binny' ,
                'Syed Shahabuddin' ,
                'Sridharan Sriram' ,
                'Steve Smith' ,
                'Aaron Finch' ,
                'Abhishek Jhunjhunwala' ,
                'Adam Voges' ,
                'Amit Paunikar' ,
                'Amit Uniyal' ,
                'Damien Martyn' ,
                'Michael Lumb' ,
                'Shrikant Wagh' ,
                'Syed Quadri' ,
                'Ben Hilfenhaus' ,
                'Francois du Plessis' ,
                'Kuthethurshri Vasudevadas' ,
                'Nuwan Kulasekara' ,
                'Suraj Randiv' ,
                'Tim Southee' ,
                'Akash Bhandari' ,
                'Anand Rajan' ,
                'Ankit Sharma' ,
                'Chris Lynn' ,
                'Daniel Christian' ,
                'Kedar Devdhar' ,
                'Ajit Chandila' ,
                'Colin Ingram' ,
                'Matthew Wade' ,
                'Prashant Naik' ,
                'Robbie Frylinck' ,
                'Robin BistX' ,
                'Shahbaz Nadeem' ,
                'Travis Birt' ,
                'Unmukt Chand' ,
                'Vikas Mishra' ,
                'Vivek Yadav' ,
                'Brad Haddin' ,
                'James Pattinson' ,
                'Mohammed Shami' ,
                'Ryan ten Doeschate' ,
                'Shakib Al Hasan' ,
                'Deepak Chougule' ,
                'Gnaneswara Rao' ,
                'John Hastings' ,
                'Michael Klinger' ,
                'Padmanabhan Prasanth' ,
                'Prasanth Parameswaran' ,
                'Sushant Marathe' ,
                'Amit Yadav' ,
                'Bhargav Bhatt' ,
                'David Miller' ,
                'Manan Vohra' ,
                'Nathan Rimmington' ,
                'Stuart Broad' ,
                'Sunny Singh' ,
                'Aiden Blizzard' ,
                'Clint McKay' ,
                'Davy Jacobs' ,
                'James Franklin' ,
                'Pawan Suyal' ,
                'Ray Price' ,
                'Santosh Yadav' ,
                'Sarul Kanwar' ,
                'Suryakumar Yadav' ,
                'Yuzvendra Chahal' ,
                'Alfonso Thomas' ,
                'Callum Ferguson' ,
                'Dheeraj Jadhav' ,
                'Eklavya Dwivedi' ,
                'Ganesh Gaikwad' ,
                'Harpreet Singh' ,
                'Imtiaz Ahmed' ,
                'James Faulkner' ,
                'Nathan McCullum' ,
                'Nayan Doshi' ,
                'Shrikant Mundhe' ,
                'Tim Paine' ,
                'Abrar Kazi' ,
                'Asad Pathan' ,
                'BN Bharath' ,
                'Johan van der Wath' ,
                'Jonathan Vandiar' ,
                'Mayank Agarwal' ,
                'Nuwan Pradeep' ,
                'Rilee Rossouw' ,
                'Syed Mohammed' ,
                'Ashok Menaria' ,
                'Deepak Chahar' ,
                'Dishant Yagnik' ,
                'Samad Fallah' ,
                'Akshath Reddy' ,
                'Biplab Samantray' ,
                'Daniel Harris' ,
                'Darren Bravo' ,
                'Sneha Kishore' ,
                'Tanmay Mishra' ,
                'Tekkami Atchuta Rao' ,
                'TP Sudhindra' ,
                'Veer Pratap Singh' ,
                'Andre Russell' ,
                'Doug Bracewell' ,
                'Glenn Maxwell' ,
                'Gulam Bodi' ,
                'Kuldeep Raval' ,
                'Manpreet Juneja' ,
                'Pawan Negi' ,
                'Puneet Bisht' ,
                'Sunny Gupta' ,
                'Zafir Patel' ,
                'Chirag Jani' ,
                'Iresh Saxena' ,
                'Marchant de Lange' ,
                'Sanju Samson' ,
                'Sunil Narine' ,
                'Ben Cutting' ,
                'Gurkeerat Singh' ,
                'Kyle Abbott' ,
                'Parvinder Awana' ,
                'Amitoze Singh' ,
                'Apoorv Wankhade' ,
                'Kuldeep Yadav' ,
                'Mitchell Johnson' ,
                'Richard Levi' ,
                'Robin Peterson' ,
                'Sujit Nayak' ,
                'Anustup Majumdar' ,
                'Krishnakant Upadhyay' ,
                'Luke Wright' ,
                'Marlon Samuels' ,
                'Michael Clarke' ,
                'Tamim Iqbal' ,
                'Harshal Patel' ,
                'Karun Nair' ,
                'S. Thiagarajan' ,
                'Vijay Zol' ,
                'Brad Hogg' ,
                'Dinesh Chandimal' ,
                'Kevon Cooper' ,
                'Samuel Badree' ,
                'Akila Dananjaya' ,
                'Ankit Rajpoot' ,
                'Baba Aparajith' ,
                'Ben Laughlin' ,
                'Chris Morris' ,
                'Jason Holder' ,
                'Mohit Sharma' ,
                'R. Karthikeyan' ,
                'Ronit More' ,
                'Vijay Shankar' ,
                'Arisht Singhvi' ,
                'Ben Rohrer' ,
                'Jeevan Mendis' ,
                'Royston Dias' ,
                'Sachithra Senanayake' ,
                'Aniket Choudhary' ,
                'Michael Neser' ,
                'Sandeep Sharma' ,
                'Axar Patel' ,
                'Jalaj Saxena' ,
                'Jasprit Bumrah' ,
                'Javed Khan' ,
                'Nathan Coulter-Nile' ,
                'Phillip Hughes' ,
                'Ishwar Pandey' ,
                'Kane Richardson' ,
                'Parvez Rasool' ,
                'Udit Birla' ,
                'Chris Barnwell' ,
                'KL Rahul' ,
                'Ravi Rampaul' ,
                'Sandeep Warrier' ,
                'Sheldon Jackson' ,
                'Kumar Boresa' ,
                'Kusal Perera' ,
                'Pravin Tambe' ,
                'Sachin Baby' ,
                'Darren Sammy' ,
                'Hanuma Vihari' ,
                'Quinton de Kock' ,
                'Thalaivan Sargunam' ,
                'Matt Henry' ,
                'HS Sharath' ,
                'Imran Tahir' ,
                'Jimmy Neesham' ,
                'Jayant Yadav' ,
                'Milind Kumar' ,
                'Pat Cummins' ,
                'Sayan Mondal' ,
                'Beuran Hendricks' ,
                'Karanveer Singh' ,
                'Shardul Thakur' ,
                'Shivam Sharma' ,
                'Ben Dunk' ,
                'Corey Anderson' ,
                'Josh Hazlewood' ,
                'Krishmar Santokie' ,
                'Lendl Simmons' ,
                'Shreyas Gopal' ,
                'Mitchell Starc' ,
                'Nic Maddinson' ,
                'Amit Mishra' ,
                'Ankush Bains' ,
                'Deepak Hooda' ,
                'Rahul Tewatia' ,
                'Brendan Taylor' ,
                'Chama Milind' ,
                'Ricky Bhui' ,
                'Andrew Tye' ,
                'Pratyush Singh' ,
                'Domnic Muthuswami' ,
                'Gurinder Sandhu' ,
                'KK Jiyas' ,
                'Marcus Stoinis' ,
                'Shreyas Iyer' ,
                'Srikar Bharat' ,
                'Travis Head' ,
                'Aditya Garhwal' ,
                'KC Cariappa' ,
                'Vaibhav Rawal' ,
                'Nikhil Naik' ,
                'Yogesh Golwalkar' ,
                'Akshay Wakhare' ,
                'Alex Hales' ,
                'Colin Munro' ,
                'Hardik Pandya' ,
                'Jagadeesha Suchith' ,
                'Mitchell McClenaghan' ,
                'Nitish Rana' ,
                'Siddhesh Lad' ,
                'Adam Milne' ,
                'David Wiese' ,
                'Sarfaraz Khan' ,
                'Sean Abbott' ,
                'Shishir Bhavane' ,
                'Barinder Sran' ,
                'Pardeep Sahu' ,
                'Sagar Trivedi' ,
                'Kane Williamson' ,
                'Trent Boult' ,
                'Akhil Herwadkar' ,
                'Carlos Brathwaite' ,
                'Khaleel Ahmed' ,
                'Rishabh Pant' ,
                'Sam Billings' ,
                'Akshdeep Nath' ,
                'Ishan Kishan' ,
                'Umang Sharma' ,
                'Armaan Jaffer' ,
                'Farhaan Behardien' ,
                'Hashim Amla' ,
                'Deepak Punia' ,
                'Jos Buttler' ,
                'Kishore Kamath' ,
                'Krunal Pandya' ,
                'Martin Guptill' ,
                'Chris Jordan' ,
                'Joel Paris' ,
                'Praveen Dubey' ,
                'Adam Zampa' ,
                'Murugan Ashwin' ,
                'Peter Handscomb' ,
                'Usman Khawaja' ,
                'Mustafizur Rahman' ,
                'Ankit Bawne' ,
                'Kagiso Rabada' ,
                'Navdeep Saini' ,
                'Basil Thampi' ,
                'Jason Roy' ,
                'Pratham Singh' ,
                'Rinku Singh' ,
                'Shubham Agarwal' ,
                'Chris Woakes' ,
                'Colin de Grandhomme' ,
                'Rovman Powell' ,
                'T Natarajan' ,
                'Krishnappa Gowtham' ,
                'Nicholas Pooran'
                'Avesh Khan' ,
                'Billy Stanlake' ,
                'Tymal Mills' ,
                'Ben Stokes' ,
                'Lockie Ferguson' ,
                'Milind Tandon' ,
                'Rahul Chahar' ,
                'Rahul Tripathi' ,
                'Saurabh Kumar' ,
                'Washington Sundar' ,
                'Mohammad Nabi' ,
                'Mohammed Siraj' ,
                'Rashid Khan' ,
                'Tanmay Agarwal' ,
                'Chaitanya Bishnoi' ,
                'David Willey' ,
                'Dhruv Shorey' ,
                'KM Asif' ,
                'Kshitiz Sharma' ,
                'Lungi Ngidi' ,
                'Mark Wood' ,
                'Mitchell Santner' ,
                'Monu Kumar' ,
                'Nayaran Jagadeesan' ,
                'Abhishek Sharma' ,
                'Junior Dala' ,
                'Liam Plunkett' ,
                'Manjot Kalra' ,
                'Prithvi Shaw' ,
                'Sandeep Lamichhane' ,
                'Cameron Delport' ,
                'Javon Searles' ,
                'Kamlesh Nagarkoti' ,
                'Prasidh Krishna' ,
                'Shivam Mavi' ,
                'Shubman Gill' ,
                'Tom Curran' ,
                'Ben Dwarshuis' ,
                'Manzoor Dar' ,
                'Mayank Dagar' ,
                'Mujeeb Ur Rahman' ,
                'Anukul Roy' ,
                'Evin Lewis' ,
                'Jason Behrendorff' ,
                'M. D. Nidheesh' ,
                'Mayank Markande' ,
                'Mohsin Khan' ,
                'Sharad Lumba' ,
                'Tajinder Singh' ,
                'Aniruddha Joshi' ,
                'Moeen Ali' ,
                'Pavan Deshpande' ,
                'Aryaman Birla' ,
                'Dushmantha Chameera' ,
                'Heinrich Klaasen' ,
                'Ish Sodhi' ,
                'Jatin Saxena' ,
                'Jofra Archer' ,
                'Mahipal Lomror' ,
                'Prashant Chopra' ,
                'Sudhesan Midhun' ,
                'Zahir Khan' ,
                'Mehdi Hasan' ,
                'Ruturaj Gaikwad' ,
                'Scott Kuggeleijn' ,
                'Bandaru Ayyappa' ,
                'Keemo Paul' ,
                'Sherfane Rutherford' ,
                'Anrich Nortje' ,
                'Harry Gurney' ,
                'Joe Denly' ,
                'Matthew Kelly' ,
                'Prithvi Raj' ,
                'Agnivesh Ayachi' ,
                'Arshdeep Singh' ,
                'Darshan Nalkande' ,
                'Hardus Viljoen' ,
                'Harpreet Brar' ,
                'Prabhsimran Singh' ,
                'Sam Curran' ,
                'Varun Chakravarthy' ,
                'Alzarri Joseph' ,
                'Anmolpreet Singh' ,
                'Pankaj Jaiswal' ,
                'Rasikh Salam Dar' ,
                'Ashton Turner' ,
                'Liam Livingstone' ,
                'Oshane Thomas' ,
                'Riyan Parag' ,
                'Shubham Ranjane' ,
                'Devdutt Padikkal' ,
                'Himmat Singh' ,
                'Prayas Ray Barman' ,
                'Shimron Hetmyer' ,
                'Shivam Dube' ,
                'Jonny Bairstow' ,
                'Ravisrinivasan Sai Kishore' ,
                'Alex Carey' ,
                'Daniel Sams' ,
                'Lalit Yadav' ,
                'Tushar Deshpande' ,
                'Ali Khan' ,
                'Chris Green' ,
                'Manimaran Siddharth' ,
                'Tom Banton' ,
                'Ishan Porel' ,
                'Ravi Bishnoi' ,
                'Sheldon Cottrell' ,
                'Digvijay Deshmukh' ,
                'Prince Balwant Rai Singh' ,
                'Isuru Udana' ,
                'Josh Philippe' ,
                'Shahbaz Ahmed' ,
                'Akash Singh' ,
                'Anuj Rawat' ,
                'Kartik Tyagi' ,
                'Yashasvi Jaiswal' ,
                'Abdul Samad' ,
                'Bavanaka Sandeep' ,
                'Fabian Allen' ,
                'Priyam Garg' ,
]
